### ISSUE TITLE
Add bore of soprano recorder

### ISSUE THREAD

**Issue by page200** [edwardkort/WWIDesigner#149]
Hi,

could you please add the bore of a usual soprano recorder, so that it can be chosen in the app?

Here are some resources, but **these resources seem to be for alto rather than soprano recorders, whereas I'd like to work with soprano recorders**:

- Info about the bore: https://www.flute-a-bec.com/percegb.html
- Attempt in WIDesigner: https://github.com/edwardkort/WWIDesigner/files/5840056/altblokfluit.zip
- Accompanying discussion regarding what should be fixed: https://github.com/edwardkort/WWIDesigner/discussions/119
- Another cross-section:
![csm_Alt-Querschnitt-NT_642c93229a](https://user-images.githubusercontent.com/69221289/171614209-7a14b6ba-ad95-4a5d-a335-a2517de85f6f.jpg)

Thank you in advance!

**Comment by bhp1** [comment]
You are welcome to use the software to create your own [instrument file](https://github.com/edwardkort/WWIDesigner/wiki/Using-WIDesigner#data-files) for a soprano recorder.  One way to do this would be to open the file altblokfluit.xml that [friedelwolff](https://github.com/friedelwolff) created and saved at https://github.com/edwardkort/WWIDesigner/files/5838477/altblokfluit.zip for an alto recorder, and replace the bore measurements and hole measurements with the measurements for a soprano recorder, measurements that you have made or someone else has made.  Philippe Bolton has provided a graph of the bore; you could read the bore measurements from his graph, but you would also need hole sizes and positions.  I do not have the measurements myself, or the means to make them accurately.
