### ISSUE TITLE
Add fingering pattern to each row of the Instrument Tuning Table

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#19]
Mike Prairie suggests adding a Fingering column to the Instrument Tuning Table.

**Comment by edwardkort** [comment]
Will be discussed between the programmers. The Tuning Table for Whistles is quite a bit wider and may not accommodate an extra column. And such a column could become very unwieldy for an instrument with many finger holes.

**Comment by bhp1** [comment]
In the whistle model, the tuning table can have up to 10 columns already.  I can't support adding another column for static information, particularly a column wide enough to render the fingering.
