### ISSUE TITLE
interesting problem

### ISSUE THREAD

**Issue by stanleyloftness** [edwardkort/WWIDesigner#34]
Pat Haran gave me the diagram for one of his G flutes at the Zion flute school.  I made one and it has a excellent extended scale, with all notes within 5 cents.  When I try to recreate it with the WWI designer, I can't get it even close to tuned.  Any idea why?

![g flute--pat haran](https://cloud.githubusercontent.com/assets/12632948/8139171/c37200aa-110e-11e5-83a1-1df73e995c6d.jpg)

**Comment by edwardkort** [comment]
Stan,
Please send me the instrument.xml and tuning.xml you created. Pay particular attention to the top-of-the-bore details, hole sizes, how many direction holes, and choke shape.

**Comment by edwardkort** [comment]
Closing issue because of no response.
