### ISSUE TITLE
Design results with stepped bore

### ISSUE THREAD

**Issue by unclebagley** [edwardkort/WWIDesigner#38]
Not an issue, more of a compliment. I thought that you might be interested in the results of a design verification exercise I ran on probably my best F#4 flute. It's made of two sizes of PVC, the thick walled stuff for the SAC exit and TSH and the thin walled stuff for the tone hole section.

A link to the screenshot of the design and results is posted below. Astounding match. It took me days to get that flute where I wanted it, and WIDesigner gave me the design in a few minutes.

![screenshot 2015-09-29 12 09 50](https://cloud.githubusercontent.com/assets/6377744/10175551/5a1e5dce-66a4-11e5-8ecf-ee6531b03d78.png)

Thank you fellows,

Barry Gordon

**Comment by edwardkort** [comment]
Barry,

Thank you for running and sharing this as-built validation scenario. The more flute geometries put through the program, the more comfortable I become with the underlying implementation.

Have you noticed any effect of the step profile on playing characteristics? WIDesigner, using a taper optimizer and multi-start optimization, will often give a step profile - which I resolve by increasing the lower bound of the taper length constraint. I have found that a taper start within the top 3 holes affects the ease of playing second octave notes.

Cheers,
Edward Kort
Wood Wind
