### ISSUE TITLE
Install in Apple desktop issue

### ISSUE THREAD

**Issue by JRSflyer** [edwardkort/WWIDesigner#39]
The software installed but it does not have an Edit-Options menu.  It also only has one menu bar at the top where Edward's video showed two.

Thanks

**Comment by edwardkort** [comment]
The Mac OS imposes certain UI constrains on WIDesigner:
1. The Options menu item is found under the application menu, and is called Preferences;
2. The Tools toolbar is not supported. You will need to use the corresponding menu items.

The above is a consequence of using an application framework that attempts to comply with the constraints imposed by each supported operating system. The videos were produced using a Windows deployment, with a different (and less stringent) set of UI constraints.

Cheers,
Edward Kort
