### ISSUE TITLE
Add more realistic mouthpiece calculator for single and double reeds

### ISSUE THREAD

**Issue by bhp1** [edwardkort/WWIDesigner#42]
At present, ReedStudyModel uses MouthpieceCalculator, which assumes reed mouthpieces are an ideal closed end.  Need a more realistic model, based on real-life measurements and any research papers that might be available.

**Comment by bhp1** [comment]
SimpleReedMouthpieceCalculator checked in, and used by SimpleReedCalculator.  Uses a simple two-parameter admittance model that agrees reasonably well with reeds tested.  Wasn't able to find anything better in the research literature.

**Comment by edwardkort** [comment]
Closed with release v2.0.0.
