### ISSUE TITLE
Add taper optimizer for instrument bells

### ISSUE THREAD

**Issue by bhp1** [edwardkort/WWIDesigner#45]
Brass instruments and some reed instruments terminate in curved horns or bells.  A bore model built from short cones can model a bell accurately enough for tuning purposes.  However, we'll need a new optimizer (or two) to optimize the profile of these bells, and the taper of any conical segment leading into the bell.  Such an optimizer could also be used for creating a bell model from scratch.

**Comment by bhp1** [comment]
BoreDiameterObjectiveFunction and BorePositionObjectiveFunction checked in.  Some changes are still called for so they can play nicely with others in a merged objective function.

**Comment by bhp1** [comment]
BoreObjectiveFunction and HoleAndBoreObjectiveFunction, with their corresponding Global versions to use the DIRECT optimizer, complete the set of objective functions for optimizing instrument bore profiles.

**Comment by edwardkort** [comment]
Closed with release v2.0.0.
