### ISSUE TITLE
Options Menu not visible on Mac

### ISSUE THREAD

**Issue by jonnorrismusic** [edwardkort/WWIDesigner#46]
I'm running WIDesigner 1.1 on a Mac with the latest OS and Java. I'd like to switch from inches to millimeters, but Options is not listed in the Edit menu, although it appears just fine on my ancient Windows machine running the same version of WIDesigner.

**Comment by edwardkort** [comment]
The WIDesigner user interface is operating system compliant. That is, it looks a bit different on Mac OS, Windows, and Linux. The Options menu item (under the Edit menu) on Windows is called Preferences (under the File menu) on the Mac.

**Comment by jonnorrismusic** [comment]
Thanks! I didn't even think to look up there.
