### ISSUE TITLE
frequency calculator

### ISSUE THREAD

**Issue by JRSflyer** [edwardkort/WWIDesigner#47]
I tried downloading your frequency calculator from yahoo groups using the url from your video and I get an opps message that it does not exist.  Can you give an alternate way to domnload it?

Thanks

Rick

**Comment by bhp1** [comment]
You should always be able to get the latest release (currently 1.1.0) from [https://github.com/edwardkort/WWIDesigner/releases/latest](https://github.com/edwardkort/WWIDesigner/releases/latest).  Look for the WIDesigner....zip file, currently [ WIDesigner-1.1.0.zip](https://github.com/edwardkort/WWIDesigner/releases/download/v1.1.0/WIDesigner-1.1.0.zip).

**Comment by turnerofwood** [comment]
On 6/17/2016 10:15 AM, bhp1 wrote:
>
> You should always be able to get the latest release (currently 1.1.0) 
> from https://github.com/edwardkort/WWIDesigner/releases/latest. Look 
> for the WIDesigner....zip file, currently WIDesigner-1.1.0.zip 
> <https://github.com/edwardkort/WWIDesigner/releases/download/v1.1.0/WIDesigner-1.1.0.zip>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/edwardkort/WWIDesigner/issues/47#issuecomment-226827635>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AP6AZEgnBM2AKiQumNc-L5PN1bCLUbVNks5qMtYfgaJpZM4I4hfo>.
>

thank you


-- 
"The world will not be destroyed by those who do evil,
but by those who watch and do nothing" - Albert Einstein

Don't Confuse my Personality with my Attitude..
My Personality is who I am. My Attitude depends on who you are.

Political Correctness is a doctrine which holds forth
the proposition that it is entirely possible to pick up
a piece of shit by the clean end!

If the next generation fails we have ourselves to blame,after all it's our job to lead the way.
