### ISSUE TITLE
Support closing the end of the bore for certain notes

### ISSUE THREAD

**Issue by bhp1** [edwardkort/WWIDesigner#56]
Playing technique for some instruments includes closing the end of the bore for certain notes.  For uilleann pipe chanters, the end of the bore is closed on the player's knee for most notes.  For overtone flutes, the end of the bore is closed with the player's finger to get alternate harmonics.

- Add openEnd boolean data member to Termination class, defaulting to true.
- Subclass ClosableFlangedOpenEndCalculator from ThickFlangedOpenEndCalculator,
and ClosableUnflangedOpenEndCalculator from UnflangedOpenEndCalculator,
returning StateVector.closedEnd() if openEnd is false.  Use these classes in SimpleReedCalculator
and FluteCalculator/WhistleCalculator, respectively.
- Add openEnd boolean data member to Fingering class, defaulting to true.
- Change Instrument.setOpenHoles to transfer openEnd from fingering to termination.
- Add allowsClosedEnd boolean data member to FingeringPattern class, defaulting to false.
- Change WhistleTuningPanel to include checkbox for allowsClosedEnd, and
when allowsClosedEnd is true, a radio button for openEnd in each fingering.
- Reed models require that at least one of the holes or the end must be open.

**Comment by edwardkort** [comment]
Alternatively, give such instruments their own studies and do not touch any of the existing code. There will be massive code reuse, and the derived classes will be trivial.

**Comment by bhp1** [comment]
From our perspective, the difference is not in the instrument but in the tuning.  The tuning includes notes for which the end of the bore is closed.  The external instrument description is no different.  In principle, this is possible with any woodwind: someone could get it into their head to stop the end of a NAF on their knee to get accidentals.

**Comment by edwardkort** [comment]
For the NAF, no useable tone is produced when the end is closed until virtually all the finger holes are opened. So I would not want to expose this capability in the NAF study.

**Comment by bhp1** [comment]
No need for allowClosableEnd member, or other changes to FingeringPattern.  Add alternate renderer/editor for fingerings with closable end: FingeringWithEndRenderer, FingeringWithEndEditor.  WhistleTuningPanel can use these alternate classes for the fingering pattern column if any of the notes have openEnd data, much as it displays min/max freq or optimization weights only if the Tuning contains them.

**Comment by bhp1** [comment]
Resolved in `modelling` branch.

**Comment by bhp1** [comment]
Merged with `master`.

**Comment by bhp1** [comment]
Released with 2.1.0.
