### ISSUE TITLE
Tuning data structure

### ISSUE THREAD

**Issue by bhp1** [edwardkort/WWIDesigner#6]
Looking at the domain, I see three main "Scale" entities:

Relative Scale
- Ultimately a sequence of relative frequencies starting at 1.0, usually but not necessarily monotonically increasing.
- This is usually standard reference scale like "Equal Temperament", but not necessarily.  To start with, however, I suggest we limit ourselves to a few standard reference scales.
- May have a sequence of corresponding note names, such as a movable doh-re-mi, but not necessarily.  I see no need to capture note names for our purposes.
- This is currently &lt;xsd:complexType name="Temperament"&gt; in Tuning.xsd.

Absolute Scale
- A relative scale plus the frequency of the base note or bell note, and generally limited to a specific number of notes.
- Usually (always?) has a sequence of corresponding note names.
- &lt;xsd:complexType name="Scale"&gt; in Tuning.xsd fills a similar purpose, but doesn't have the connection to
a Relative Scale or Temperament.

Played Scale
- A fixed length sequence of playing configurations, all of the same type.
- &lt;xsd:complexType name="FingeringPattern"&gt; in Tuning.xsd is _one possible type_ of played scale.

Where a Playing Configuration is one of the possible dispositions a player can make with a specific instrument, intended to play a specific (relative) note.
- A given instrument will have a specific datatype for its playing configurations.  Different instruments may have different datatypes. In particular, the datatype is specific to the number of toneholes.
- _One_ possible datatype, suitable for a 6-hole whistle, is:
    - Finger pattern: a sequence of 6 tonehole states: open or closed, or possibly half-open.
    - Register number: 1 for fundamental, 2 for first overblown note, etc.

Only when you get to a specific instrument is there a relationship between the Played Scale of that instrument, and an Absolute Scale of target notes.  In particular, conventional whistles all share pretty much the same two-octave Played Scale, but only a certain subset of whistles are designed to give a high-D Equal Temperament absolute scale from that played scale.

**Comment by edwardkort** [comment]
The addition of Weights to the Tuning definition answers to distinction between Played and Absolute scales.
