### ISSUE TITLE
The current number of starts for NAF multi-start optimizations is often too large

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#62]
If the bore-length constraint is reduced, the current 30 starts is often not needed to ensure finding the best solution.

**Comment by edwardkort** [comment]
Added a preference and spinner on the NafStudy tab of the Options dialog, and use the value for the number of starts in the NafStudy in the range [1, 50].

**Comment by bhp1** [comment]
Released with 2.1.0.
