### ISSUE TITLE
Graph note spectrum action's enabled is not set correctly

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#63]
The Graph note spectrum action is enabled whenever a tuning is selected. This throws an exception if an instrument is not selected. The action should not be enabled unless both an instrument and tuning are selected.

**Comment by bhp1** [comment]
Resolved on `modelling` branch.

**Comment by bhp1** [comment]
Merged into `master`.

**Comment by bhp1** [comment]
Released with 2.1.0.
