### ISSUE TITLE
Save as dialog for XML files shows .xml.xml

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#64]
A bug recently introduced in the JDAF library causes this behavior when doing a Save as with an existing XML file.

**Comment by edwardkort** [comment]
JideSoft posted a new release (jide.3.6.19 and jdaf.2.4.28) that fixes this bug.

These libraries will be included in the next release: 2.1.0

**Comment by bhp1** [comment]
Released with 2.1.0.
