### ISSUE TITLE
NAF editor view tables are too small

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#74]
In the NAF Tuning view pane, the tuning table is too small to see all the fields when there are more than 6 holes, required lots of back and forth horizontal scrolling.

In the NAF Instrument view pane, the hole table is too small to see the entire hole name if it is more than a few characters long.

**Comment by edwardkort** [comment]
Fixed in commit on June 19, 2018. Will be part of the 2.2.0 release.

**Comment by bhp1** [comment]
Included in 2.2.0 release.
