### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by edwardkort** [edwardkort/WWIDesigner#78]
Using the default compiler error/warning settings, the project compiles cleanly. However, many settings are set to "Ignore". Explore/fix these ignorable settings.

**Comment by edwardkort** [comment]
All of the reasonable (IMHO) error and warning checks have been implemented in the compiler, and the code compiles cleanly and passes all JUnit tests. No functional errors were found in the code fixes.

Changes will be in the next release.

**Comment by bhp1** [comment]
Included in 2.2.0 release.
